Cora:
  seed: 39788
  learning_rate: 0.01
  input_dim: 1433
  hidden: 128
  proj_middim: 128
  proj_outdim: 128
  encoder: gat
  layer_num: 2
  walk_step: 10
  restart_ratio: 0.5
  graph_num: 128
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.3
  tau: 0.4
  epochs: 500
  weight_decay: 0.0005
  optimizer: sgd
  patience: 500
  inductive: False
Citeseer:
  seed: 38108
  learning_rate: 0.01
  input_dim: 3703
  hidden: 256
  proj_middim: 256
  proj_outdim: 256
  encoder: gat
  layer_num: 2
  walk_step: 10
  restart_ratio: 0.5
  graph_num: 128
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.4
  drop_feature_rate_2: 0.5
  tau: 0.7
  epochs: 300
  weight_decay: 0.0005
  optimizer: sgd
  patience: 300
  inductive: False
Amazon-Photo:
  seed: 39789
  learning_rate: 0.001
  input_dim: 745
  hidden: 256
  proj_middim: 128
  proj_outdim: 128
  encoder: gat
  layer_num: 2
  walk_step: 10
  restart_ratio: 0.5
  graph_num: 128
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.3
  tau: 0.3
  epochs: 500
  weight_decay: 0.0005
  optimizer: adamw
  patience: 500
  inductive: False
Amazon-Computers:
  seed: 39780
  learning_rate: 0.001
  input_dim: 767
  hidden: 128
  proj_middim: 128
  proj_outdim: 128
  encoder: gat
  layer_num: 2
  walk_step: 10
  restart_ratio: 0.5
  graph_num: 128
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  tau: 0.2
  epochs: 500
  weight_decay: 0.0005
  optimizer: adamw
  patience: 500
  inductive: False

